### ISSUE TITLE
Crash while setting keybinds

### ISSUE THREAD

**Issue by Sea3Plays** [VanillaEngineDevs/Vanilla-Engine#18] opened 2023-08-28 03:00 UTC
I got this error when I was trying to put my keybinds in.
Error

lib/baton.lua:63: Invalid key constant:  

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'isDown'
lib/baton.lua:63: in function <lib/baton.lua:62>
lib/baton.lua:217: in function '_setActiveDevice'
lib/baton.lua:351: in function 'update'
main.lua:625: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by Sea3Plays** [comment] 2023-08-28 03:01
Oh yea and it doesnt work anymore so I can use it.

**Comment by GuglioIsStupid** [comment] 2023-08-28 03:05
What did you try setting your keybinds to? If you used a special character probably won't work until I add a check for it

**Comment by GuglioIsStupid** [comment] 2023-08-28 03:07
Try deleting the settings file found in the save folder, then try setting it to a different combo to see if the issue is thay

**Comment by GuglioIsStupid** [comment] 2023-09-01 13:59
Any update on this? Will not be closing as a reminder to add a check

**Closed** 2024-05-04 16:07 UTC
